### ISSUE TITLE
PlotlyKaleido.start() sometimes hangs on windows

### ISSUE THREAD

**Issue by disberd** [JuliaPlots/PlotlyKaleido.jl#13]
I have faced the issue mentioned in https://github.com/JuliaPlots/PlotlyJS.jl/issues/473 when trying to start PlotlyKaleido on a windows machine.

I have reproduced this issue both on 1.9.3 and on 1.10-beta3, by simply activating a temp environment with just PlotlyKaleido and then just calling `PlotlyKaleido.start()` (after `using PlotlyKaleido`).
The REPL seems to hang indefinitely until explicitly interrupted with Ctrl-C. After interrupting, calling `PlotlyKaleido.start()` does not hang while `PlotlyKaleido.restart()` does.

This seems to be an intermittent problem, as it does not always happen every time I try to reproduce it

**Comment by RoyiAvital** [comment]
Could it be related to https://github.com/JuliaPlots/PlotlyJS.jl/issues/479 ?
