### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaPlots/PlotlyKaleido.jl#2]
We clash names with https://github.com/tkf/Kaleido.jl
Other good name suggestions? @joshday, @sglyon

**Comment by BeastyBlacksmith** [comment]
PlotlySave.jl exists already, Savefig.jl would still be available, but is maybe a bit too broad.
PlotlyFile.jl or Plotly2File.jl would also be available.

**Comment by sglyon** [comment]
Maybe we coordinate with @hhaensel to use PlotlySave.jl?

**Comment by joshday** [comment]
PlotlyKaleido?

It looks like PlotlySave implements `FileIO.save`, which we would be unable to do since the types we need live in different packages.

**Comment by hhaensel** [comment]
Hi,
Not sure what the scope of that packages shall be. If it is identical to mine, feel free to take over PlotlySave.
I offered this already some time ago before I registered the Package.
In that case I propose that PlotlySave is migrated to JuliaPlots

**Comment by BeastyBlacksmith** [comment]
The scope of this package is much narrower than that of the current PlotlySave, it takes a valid plotlyplot json string and creates an output file from it, if you don't intend to develop/maintain it we could move it to JuliaPlots,  make a breaking realease and replace it with this version of the package since according to juliahub PlotlySave has 0 Dependents.

Otherwise PlotlyKaleido would also work for me.

**Comment by joshday** [comment]
My vote would be to register this repo as PlotlyKaleido as the path of least resistance.

**Comment by hhaensel** [comment]
If you are interested you can migrate the Package to JuliaPlots and publish a new version.
Wouldn't you think that it's interesting to keep the savefig command as is?

I understand that the definition of FileIO.save() is strictly speaking type piracy, although I still find the syntax tempting. Not sure, how a correct way out could look like. Perhaps by defining a format type that resides within PlotlySave and which is mandatory when calling FileIO.save ...?
Let me know what you think.

**Comment by BeastyBlacksmith** [comment]
I've gone with PlotlyKaleido now, since I do find it awkward to change the scope of a package between major-versions.

**Comment by BeastyBlacksmith** [comment]
https://github.com/JuliaRegistries/General/pull/67704 🎉
