### ISSUE TITLE
How to specify plotly version

### ISSUE THREAD

**Issue by disberd** [JuliaPlots/PlotlyKaleido.jl#7]
I was using PlotlyKaleido today to save a figure that I generated using the latest version of Plotly (2.25.1)

When trying to save the Plot object using PlotlyKaleido, the figure is slightly difference.

More specifically I used the `tickmode = sync` option that was added in version 2.18.0 of plotly to have matching ticks between two y axis but while this works correctly on the plot object rendered on the Pluto notebook, this does not result from the generated image from `savefig`, making me believe that kaleido is internally using a version of plotly that is older than 2.18.

Is there a way to specify which version of plotly to use?

**Comment by BeastyBlacksmith** [comment]
My guess is, that we need a new build of Kaleido_jll
